/* ================================================================
 * Helvetia — Documents Module
 * Auto-generated by gen_modules.py
 * ================================================================ */
#include "documents_module.h"
#include <stddef.h>

static const HelvetiaTool tools_word_processing[] = {
    { "docx_viewer", "DOCX Viewer", "DOCX Viewer", "x-office-document-symbolic", (const char*[]){ "docx", "viewer", "documents", NULL }, "docx-viewer", NULL },
    { "docx_editor", "DOCX Editor", "basic", "x-office-document-symbolic", (const char*[]){ "docx", "editor", "documents", NULL }, "docx-editor", NULL },
    { "docx_to_pdf", "DOCX to PDF", "DOCX to PDF", "x-office-document-symbolic", (const char*[]){ "docx", "documents", "pdf", NULL }, "docx2pdf", NULL },
    { "docx_to_markdown", "DOCX to Markdown", "DOCX to Markdown", "x-office-document-symbolic", (const char*[]){ "docx", "markdown", "documents", NULL }, "docx2markdown", NULL },
    { "docx_to_html", "DOCX to HTML", "DOCX to HTML", "x-office-document-symbolic", (const char*[]){ "documents", "docx", "html", NULL }, "docx2html", NULL },
    { "docx_to_txt", "DOCX to TXT", "DOCX to TXT", "x-office-document-symbolic", (const char*[]){ "documents", "docx", "txt", NULL }, "docx2txt", NULL },
    { "txt_to_docx", "TXT to DOCX", "TXT to DOCX", "x-office-document-symbolic", (const char*[]){ "documents", "docx", "txt", NULL }, "txt2docx", NULL },
    { "markdown_to_docx", "Markdown to DOCX", "Markdown to DOCX", "x-office-document-symbolic", (const char*[]){ "docx", "markdown", "documents", NULL }, "markdown2docx", NULL },
    { "odt_converter", "ODT Converter", "ODT Converter", "text-x-generic-symbolic", (const char*[]){ "odt", "converter", "documents", NULL }, "odt-converter", NULL },
    { NULL }
};

static const HelvetiaTool tools_spreadsheets[] = {
    { "xlsx_viewer", "XLSX Viewer", "XLSX Viewer", "x-office-spreadsheet-symbolic", (const char*[]){ "documents", "viewer", "xlsx", NULL }, "xlsx-viewer", NULL },
    { "xlsx_to_pdf", "XLSX to PDF", "XLSX to PDF", "x-office-spreadsheet-symbolic", (const char*[]){ "documents", "xlsx", "pdf", NULL }, "xlsx2pdf", NULL },
    { "xlsx_to_csv", "XLSX to CSV", "XLSX to CSV", "x-office-spreadsheet-symbolic", (const char*[]){ "documents", "xlsx", "csv", NULL }, "xlsx2csv", NULL },
    { "csv_to_xlsx", "CSV to XLSX", "CSV to XLSX", "x-office-spreadsheet-symbolic", (const char*[]){ "xlsx", "documents", "csv", NULL }, "csv2xlsx", NULL },
    { "csv_viewer_editor", "CSV Viewer / Editor", "CSV Viewer / Editor", "x-office-spreadsheet-symbolic", (const char*[]){ "documents", "editor", "viewer", "csv", NULL }, "csv-viewer-editor", NULL },
    { "csv_to_json", "CSV to JSON", "CSV to JSON", "x-office-spreadsheet-symbolic", (const char*[]){ "documents", "json", "csv", NULL }, "csv2json", NULL },
    { "json_to_csv", "JSON to CSV", "JSON to CSV", "x-office-spreadsheet-symbolic", (const char*[]){ "documents", "json", "csv", NULL }, "json2csv", NULL },
    { "ods_converter", "ODS Converter", "ODS Converter", "text-x-generic-symbolic", (const char*[]){ "ods", "converter", "documents", NULL }, "ods-converter", NULL },
    { "spreadsheet_merger", "Spreadsheet Merger", "Spreadsheet Merger", "x-office-spreadsheet-symbolic", (const char*[]){ "spreadsheet", "documents", "merger", NULL }, "spreadsheet-merger", NULL },
    { NULL }
};

static const HelvetiaTool tools_presentations[] = {
    { "pptx_viewer", "PPTX Viewer", "PPTX Viewer", "x-office-presentation-symbolic", (const char*[]){ "documents", "pptx", "viewer", NULL }, "pptx-viewer", NULL },
    { "pptx_to_pdf", "PPTX to PDF", "PPTX to PDF", "x-office-presentation-symbolic", (const char*[]){ "pptx", "documents", "pdf", NULL }, "pptx2pdf", NULL },
    { "pptx_to_images", "PPTX to Images", "PPTX to Images", "x-office-presentation-symbolic", (const char*[]){ "pptx", "documents", "images", NULL }, "pptx2images", NULL },
    { "odp_converter", "ODP Converter", "ODP Converter", "text-x-generic-symbolic", (const char*[]){ "odp", "converter", "documents", NULL }, "odp-converter", NULL },
    { NULL }
};

static const HelvetiaTool tools_ebooks[] = {
    { "epub_reader", "EPUB Reader", "EPUB Reader", "text-x-generic-symbolic", (const char*[]){ "epub", "reader", "documents", NULL }, "epub-reader", NULL },
    { "epub_editor", "EPUB Editor", "EPUB Editor", "text-x-generic-symbolic", (const char*[]){ "epub", "editor", "documents", NULL }, "epub-editor", NULL },
    { "epub_to_pdf", "EPUB to PDF", "EPUB to PDF", "text-x-generic-symbolic", (const char*[]){ "epub", "documents", "pdf", NULL }, "epub2pdf", NULL },
    { "epub_to_mobi", "EPUB to MOBI", "EPUB to MOBI", "text-x-generic-symbolic", (const char*[]){ "epub", "documents", "mobi", NULL }, "epub2mobi", NULL },
    { "mobi_to_epub", "MOBI to EPUB", "MOBI to EPUB", "text-x-generic-symbolic", (const char*[]){ "epub", "documents", "mobi", NULL }, "mobi2epub", NULL },
    { "epub_metadata_editor", "EPUB Metadata Editor", "EPUB Metadata Editor", "text-x-generic-symbolic", (const char*[]){ "epub", "documents", "editor", "metadata", NULL }, "epub-metadata-editor", NULL },
    { "comic_reader", "Comic Reader", "CBZ, CBR", "text-x-generic-symbolic", (const char*[]){ "reader", "documents", "comic", NULL }, "comic-reader", NULL },
    { "comic_converter", "Comic Converter", "Comic Converter", "text-x-generic-symbolic", (const char*[]){ "converter", "documents", "comic", NULL }, "comic-converter", NULL },
    { NULL }
};

static const HelvetiaTool tools_markup[] = {
    { "markdown_editor", "Markdown Editor", "Markdown Editor", "text-x-generic-symbolic", (const char*[]){ "editor", "markdown", "documents", NULL }, "markdown-editor", NULL },
    { "markdown_previewer", "Markdown Previewer", "Markdown Previewer", "text-x-generic-symbolic", (const char*[]){ "markdown", "documents", "previewer", NULL }, "markdown-previewer", NULL },
    { "html_viewer", "HTML Viewer", "HTML Viewer", "text-x-generic-symbolic", (const char*[]){ "html", "viewer", "documents", NULL }, "html-viewer", NULL },
    { "html_editor", "HTML Editor", "HTML Editor", "text-x-generic-symbolic", (const char*[]){ "html", "editor", "documents", NULL }, "html-editor", NULL },
    { "html_to_pdf", "HTML to PDF", "HTML to PDF", "text-x-generic-symbolic", (const char*[]){ "html", "documents", "pdf", NULL }, "html2pdf", NULL },
    { "html_to_markdown", "HTML to Markdown", "HTML to Markdown", "text-x-generic-symbolic", (const char*[]){ "html", "markdown", "documents", NULL }, "html2markdown", NULL },
    { "rst_converter", "RST Converter", "RST Converter", "text-x-generic-symbolic", (const char*[]){ "rst", "converter", "documents", NULL }, "rst-converter", NULL },
    { "latex_to_pdf", "LaTeX to PDF", "LaTeX to PDF", "text-x-generic-symbolic", (const char*[]){ "latex", "documents", "pdf", NULL }, "latex2pdf", NULL },
    { "pdf_to_latex", "PDF to LaTeX", "PDF to LaTeX", "text-x-generic-symbolic", (const char*[]){ "latex", "documents", "pdf", NULL }, "pdf2latex", NULL },
    { NULL }
};

static const HelvetiaTool tools_office_utilities[] = {
    { "document_metadata_editor", "Document Metadata Editor", "Document Metadata Editor", "text-x-generic-symbolic", (const char*[]){ "document", "editor", "metadata", "documents", NULL }, "document-metadata-editor", NULL },
    { "document_compare", "Document Compare", "Document Compare", "text-x-generic-symbolic", (const char*[]){ "document", "compare", "documents", NULL }, "document-compare", NULL },
    { "document_merger", "Document Merger", "Document Merger", "text-x-generic-symbolic", (const char*[]){ "document", "documents", "merger", NULL }, "document-merger", NULL },
    { "document_splitter", "Document Splitter", "Document Splitter", "text-x-generic-symbolic", (const char*[]){ "document", "splitter", "documents", NULL }, "document-splitter", NULL },
    { "document_watermark", "Document Watermark", "Document Watermark", "text-x-generic-symbolic", (const char*[]){ "document", "documents", "watermark", NULL }, "document-watermark", NULL },
    { "document_redaction", "Document Redaction", "Document Redaction", "text-x-generic-symbolic", (const char*[]){ "document", "redaction", "documents", NULL }, "document-redaction", NULL },
    { "document_ocr", "Document OCR", "Document OCR", "text-x-generic-symbolic", (const char*[]){ "ocr", "document", "documents", NULL }, "document-ocr", NULL },
    { NULL }
};

static const HelvetiaSubcategory documents_subcategories[] = {
    { "Word Processing", tools_word_processing },
    { "Spreadsheets", tools_spreadsheets },
    { "Presentations", tools_presentations },
    { "Ebooks", tools_ebooks },
    { "Markup", tools_markup },
    { "Office Utilities", tools_office_utilities },
    { NULL, NULL }
};

static const HelvetiaModule documents_module = {
    .id            = "documents",
    .name          = "Documents",
    .icon_name     = "text-x-generic-symbolic",
    .description   = "Office and text document tools.",
    .subcategories = documents_subcategories,
    .create_view   = NULL,
    .on_activate   = NULL,
    .on_deactivate = NULL,
    .on_shutdown   = NULL,
};

const HelvetiaModule *helvetia_documents_get_module(void) {
    return &documents_module;
}
