/* ================================================================
 * Helvetia — Images Module
 * Auto-generated by gen_modules.py
 * ================================================================ */
#include "images_module.h"
#include <stddef.h>

static const HelvetiaTool tools_viewing[] = {
    { "image_viewer", "Image Viewer", "Image Viewer", "eog-symbolic", (const char*[]){ "image", "viewer", "images", NULL }, "image-viewer", NULL },
    { "image_slideshow", "Image Slideshow", "Image Slideshow", "image-x-generic-symbolic", (const char*[]){ "image", "images", "slideshow", NULL }, "image-slideshow", NULL },
    { "image_thumbnail_grid", "Image Thumbnail Grid", "Image Thumbnail Grid", "image-x-generic-symbolic", (const char*[]){ "thumbnail", "image", "images", "grid", NULL }, "image-thumbnail-grid", NULL },
    { "exif_viewer", "EXIF Viewer", "EXIF Viewer", "eog-symbolic", (const char*[]){ "exif", "viewer", "images", NULL }, "exif-viewer", NULL },
    { "metadata_inspector", "Metadata Inspector", "Metadata Inspector", "image-x-generic-symbolic", (const char*[]){ "inspector", "metadata", "images", NULL }, "metadata-inspector", NULL },
    { NULL }
};

static const HelvetiaTool tools_basic_editing[] = {
    { "crop", "Crop", "Crop", "crop-symbolic", (const char*[]){ "crop", "images", NULL }, "crop", NULL },
    { "resize", "Resize", "Resize", "image-x-generic-symbolic", (const char*[]){ "resize", "images", NULL }, "resize", NULL },
    { "rotate", "Rotate", "Rotate", "image-x-generic-symbolic", (const char*[]){ "rotate", "images", NULL }, "rotate", NULL },
    { "flip", "Flip", "Flip", "image-x-generic-symbolic", (const char*[]){ "flip", "images", NULL }, "flip", NULL },
    { "straighten", "Straighten", "Straighten", "image-x-generic-symbolic", (const char*[]){ "images", "straighten", NULL }, "straighten", NULL },
    { "perspective_correct", "Perspective Correct", "Perspective Correct", "image-x-generic-symbolic", (const char*[]){ "perspective", "images", "correct", NULL }, "perspective-correct", NULL },
    { "canvas_resize", "Canvas Resize", "Canvas Resize", "image-x-generic-symbolic", (const char*[]){ "canvas", "resize", "images", NULL }, "canvas-resize", NULL },
    { "auto_crop_borders", "Auto-crop Borders", "Auto-crop Borders", "crop-symbolic", (const char*[]){ "autocrop", "borders", "images", NULL }, "auto-crop-borders", NULL },
    { NULL }
};

static const HelvetiaTool tools_adjustments[] = {
    { "brightness_contrast", "Brightness / Contrast", "Brightness / Contrast", "color-select-symbolic", (const char*[]){ "brightness", "contrast", "images", NULL }, "brightness-contrast", NULL },
    { "levels", "Levels", "Levels", "image-x-generic-symbolic", (const char*[]){ "images", "levels", NULL }, "levels", NULL },
    { "curves", "Curves", "Curves", "image-x-generic-symbolic", (const char*[]){ "curves", "images", NULL }, "curves", NULL },
    { "exposure", "Exposure", "Exposure", "image-x-generic-symbolic", (const char*[]){ "exposure", "images", NULL }, "exposure", NULL },
    { "saturation_vibrance", "Saturation / Vibrance", "Saturation / Vibrance", "image-x-generic-symbolic", (const char*[]){ "vibrance", "images", "saturation", NULL }, "saturation-vibrance", NULL },
    { "hue_shift", "Hue Shift", "Hue Shift", "color-select-symbolic", (const char*[]){ "images", "hue", "shift", NULL }, "hue-shift", NULL },
    { "white_balance", "White Balance", "White Balance", "image-x-generic-symbolic", (const char*[]){ "images", "white", "balance", NULL }, "white-balance", NULL },
    { "color_balance", "Color Balance", "Color Balance", "color-select-symbolic", (const char*[]){ "color", "images", "balance", NULL }, "color-balance", NULL },
    { "shadows_highlights", "Shadows / Highlights", "Shadows / Highlights", "image-x-generic-symbolic", (const char*[]){ "shadows", "highlights", "images", NULL }, "shadows-highlights", NULL },
    { "gamma_correction", "Gamma Correction", "Gamma Correction", "image-x-generic-symbolic", (const char*[]){ "correction", "images", "gamma", NULL }, "gamma-correction", NULL },
    { "auto_enhance", "Auto Enhance", "Auto Enhance", "image-x-generic-symbolic", (const char*[]){ "images", "auto", "enhance", NULL }, "auto-enhance", NULL },
    { "histogram", "Histogram", "Histogram", "image-x-generic-symbolic", (const char*[]){ "histogram", "images", NULL }, "histogram", NULL },
    { NULL }
};

static const HelvetiaTool tools_filters[] = {
    { "blur", "Blur", "Gaussian, motion, radial", "image-x-generic-symbolic", (const char*[]){ "blur", "images", NULL }, "blur", NULL },
    { "sharpen", "Sharpen", "Sharpen", "image-x-generic-symbolic", (const char*[]){ "sharpen", "images", NULL }, "sharpen", NULL },
    { "unsharp_mask", "Unsharp Mask", "Unsharp Mask", "image-x-generic-symbolic", (const char*[]){ "images", "mask", "unsharp", NULL }, "unsharp-mask", NULL },
    { "noise_reduction", "Noise Reduction", "Noise Reduction", "image-x-generic-symbolic", (const char*[]){ "noise", "images", "reduction", NULL }, "noise-reduction", NULL },
    { "denoise", "Denoise", "Denoise", "image-x-generic-symbolic", (const char*[]){ "denoise", "images", NULL }, "denoise", NULL },
    { "sepia", "Sepia", "Sepia", "image-x-generic-symbolic", (const char*[]){ "images", "sepia", NULL }, "sepia", NULL },
    { "grayscale", "Grayscale", "Grayscale", "image-x-generic-symbolic", (const char*[]){ "grayscale", "images", NULL }, "grayscale", NULL },
    { "invert", "Invert", "Invert", "image-x-generic-symbolic", (const char*[]){ "invert", "images", NULL }, "invert", NULL },
    { "posterize", "Posterize", "Posterize", "image-x-generic-symbolic", (const char*[]){ "images", "posterize", NULL }, "posterize", NULL },
    { "threshold", "Threshold", "Threshold", "image-x-generic-symbolic", (const char*[]){ "threshold", "images", NULL }, "threshold", NULL },
    { "vignette", "Vignette", "Vignette", "image-x-generic-symbolic", (const char*[]){ "images", "vignette", NULL }, "vignette", NULL },
    { "film_grain", "Film Grain", "Film Grain", "image-x-generic-symbolic", (const char*[]){ "grain", "images", "film", NULL }, "film-grain", NULL },
    { "glow", "Glow", "Glow", "image-x-generic-symbolic", (const char*[]){ "glow", "images", NULL }, "glow", NULL },
    { "emboss", "Emboss", "Emboss", "image-x-generic-symbolic", (const char*[]){ "images", "emboss", NULL }, "emboss", NULL },
    { "edge_detect", "Edge Detect", "Edge Detect", "image-x-generic-symbolic", (const char*[]){ "edge", "detect", "images", NULL }, "edge-detect", NULL },
    { "pixelate", "Pixelate", "Pixelate", "image-x-generic-symbolic", (const char*[]){ "pixelate", "images", NULL }, "pixelate", NULL },
    { "mosaic", "Mosaic", "Mosaic", "image-x-generic-symbolic", (const char*[]){ "mosaic", "images", NULL }, "mosaic", NULL },
    { NULL }
};

static const HelvetiaTool tools_drawing_compositing[] = {
    { "brush_tool", "Brush Tool", "Brush Tool", "image-x-generic-symbolic", (const char*[]){ "images", "tool", "brush", NULL }, "brush-tool", NULL },
    { "eraser", "Eraser", "Eraser", "image-x-generic-symbolic", (const char*[]){ "images", "eraser", NULL }, "eraser", NULL },
    { "fill_bucket", "Fill / Bucket", "Fill / Bucket", "image-x-generic-symbolic", (const char*[]){ "fill", "images", "bucket", NULL }, "fill-bucket", NULL },
    { "gradient_tool", "Gradient Tool", "Gradient Tool", "image-x-generic-symbolic", (const char*[]){ "gradient", "tool", "images", NULL }, "gradient-tool", NULL },
    { "text_tool", "Text Tool", "Text Tool", "image-x-generic-symbolic", (const char*[]){ "tool", "text", "images", NULL }, "text-tool", NULL },
    { "shape_tool", "Shape Tool", "rectangle, ellipse, polygon, line", "image-x-generic-symbolic", (const char*[]){ "images", "tool", "shape", NULL }, "shape-tool", NULL },
    { "arrow_tool", "Arrow Tool", "Arrow Tool", "image-x-generic-symbolic", (const char*[]){ "arrow", "tool", "images", NULL }, "arrow-tool", NULL },
    { "eyedropper", "Eyedropper", "Eyedropper", "image-x-generic-symbolic", (const char*[]){ "images", "eyedropper", NULL }, "eyedropper", NULL },
    { "clone_stamp", "Clone Stamp", "Clone Stamp", "image-x-generic-symbolic", (const char*[]){ "clone", "images", "stamp", NULL }, "clone-stamp", NULL },
    { "healing_brush", "Healing Brush", "Healing Brush", "image-x-generic-symbolic", (const char*[]){ "healing", "images", "brush", NULL }, "healing-brush", NULL },
    { "smudge_tool", "Smudge Tool", "Smudge Tool", "image-x-generic-symbolic", (const char*[]){ "smudge", "tool", "images", NULL }, "smudge-tool", NULL },
    { "dodge_burn", "Dodge / Burn", "Dodge / Burn", "image-x-generic-symbolic", (const char*[]){ "dodge", "burn", "images", NULL }, "dodge-burn", NULL },
    { "selection_tools", "Selection Tools", "rect, ellipse, lasso, magic wand", "image-x-generic-symbolic", (const char*[]){ "tools", "selection", "images", NULL }, "selection-tools", NULL },
    { "layer_manager", "Layer Manager", "Layer Manager", "image-x-generic-symbolic", (const char*[]){ "manager", "layer", "images", NULL }, "layer-manager", NULL },
    { "layer_masks", "Layer Masks", "Layer Masks", "image-x-generic-symbolic", (const char*[]){ "layer", "images", "masks", NULL }, "layer-masks", NULL },
    { "blend_modes", "Blend Modes", "Blend Modes", "image-x-generic-symbolic", (const char*[]){ "modes", "images", "blend", NULL }, "blend-modes", NULL },
    { "opacity_control", "Opacity Control", "Opacity Control", "image-x-generic-symbolic", (const char*[]){ "control", "opacity", "images", NULL }, "opacity-control", NULL },
    { NULL }
};

static const HelvetiaTool tools_transform[] = {
    { "scale", "Scale", "Scale", "image-x-generic-symbolic", (const char*[]){ "scale", "images", NULL }, "scale", NULL },
    { "skew", "Skew", "Skew", "image-x-generic-symbolic", (const char*[]){ "skew", "images", NULL }, "skew", NULL },
    { "distort", "Distort", "Distort", "image-x-generic-symbolic", (const char*[]){ "distort", "images", NULL }, "distort", NULL },
    { "warp", "Warp", "Warp", "image-x-generic-symbolic", (const char*[]){ "warp", "images", NULL }, "warp", NULL },
    { "free_transform", "Free Transform", "Free Transform", "image-x-generic-symbolic", (const char*[]){ "images", "transform", "free", NULL }, "free-transform", NULL },
    { NULL }
};

static const HelvetiaTool tools_retouching[] = {
    { "background_removal", "Background Removal", "Background Removal", "image-x-generic-symbolic", (const char*[]){ "background", "removal", "images", NULL }, "background-removal", NULL },
    { "background_replace", "Background Replace", "Background Replace", "image-x-generic-symbolic", (const char*[]){ "background", "images", "replace", NULL }, "background-replace", NULL },
    { "portrait_retouch", "Portrait Retouch", "Portrait Retouch", "image-x-generic-symbolic", (const char*[]){ "portrait", "retouch", "images", NULL }, "portrait-retouch", NULL },
    { "blemish_removal", "Blemish Removal", "Blemish Removal", "image-x-generic-symbolic", (const char*[]){ "blemish", "removal", "images", NULL }, "blemish-removal", NULL },
    { "red_eye_removal", "Red-eye Removal", "Red-eye Removal", "image-x-generic-symbolic", (const char*[]){ "removal", "images", "redeye", NULL }, "red-eye-removal", NULL },
    { "teeth_whitening", "Teeth Whitening", "Teeth Whitening", "image-x-generic-symbolic", (const char*[]){ "teeth", "whitening", "images", NULL }, "teeth-whitening", NULL },
    { "skin_smoothing", "Skin Smoothing", "Skin Smoothing", "image-x-generic-symbolic", (const char*[]){ "smoothing", "images", "skin", NULL }, "skin-smoothing", NULL },
    { NULL }
};

static const HelvetiaTool tools_composition[] = {
    { "collage_maker", "Collage Maker", "Collage Maker", "image-x-generic-symbolic", (const char*[]){ "images", "maker", "collage", NULL }, "collage-maker", NULL },
    { "grid_layout", "Grid Layout", "Grid Layout", "image-x-generic-symbolic", (const char*[]){ "layout", "images", "grid", NULL }, "grid-layout", NULL },
    { "panorama_stitch", "Panorama Stitch", "Panorama Stitch", "image-x-generic-symbolic", (const char*[]){ "panorama", "images", "stitch", NULL }, "panorama-stitch", NULL },
    { "hdr_merge", "HDR Merge", "HDR Merge", "image-x-generic-symbolic", (const char*[]){ "hdr", "merge", "images", NULL }, "hdr-merge", NULL },
    { "focus_stack", "Focus Stack", "Focus Stack", "image-x-generic-symbolic", (const char*[]){ "images", "focus", "stack", NULL }, "focus-stack", NULL },
    { "image_stack", "Image Stack", "Image Stack", "image-x-generic-symbolic", (const char*[]){ "image", "images", "stack", NULL }, "image-stack", NULL },
    { "watermark", "Watermark", "text/image", "image-x-generic-symbolic", (const char*[]){ "images", "watermark", NULL }, "watermark", NULL },
    { "border_frame", "Border / Frame", "Border / Frame", "image-x-generic-symbolic", (const char*[]){ "frame", "border", "images", NULL }, "border-frame", NULL },
    { "drop_shadow", "Drop Shadow", "Drop Shadow", "image-x-generic-symbolic", (const char*[]){ "drop", "images", "shadow", NULL }, "drop-shadow", NULL },
    { "reflection", "Reflection", "Reflection", "image-x-generic-symbolic", (const char*[]){ "reflection", "images", NULL }, "reflection", NULL },
    { NULL }
};

static const HelvetiaTool tools_format_conversion[] = {
    { "format_converter", "Format Converter", "PNG, JPG, WEBP, AVIF, HEIC, TIFF, BMP, GIF, SVG, ICO", "image-x-generic-symbolic", (const char*[]){ "format", "converter", "images", NULL }, "format-converter", NULL },
    { "batch_convert", "Batch Convert", "Batch Convert", "image-x-generic-symbolic", (const char*[]){ "batch", "convert", "images", NULL }, "batch-convert", NULL },
    { "heic_to_jpg", "HEIC to JPG", "HEIC to JPG", "image-x-generic-symbolic", (const char*[]){ "heic", "images", "jpg", NULL }, "heic2jpg", NULL },
    { "raw_to_jpg", "RAW to JPG", "LibRaw", "image-x-generic-symbolic", (const char*[]){ "images", "raw", "jpg", NULL }, "raw2jpg", NULL },
    { "svg_to_png", "SVG to PNG", "SVG to PNG", "image-x-generic-symbolic", (const char*[]){ "png", "svg", "images", NULL }, "svg2png", NULL },
    { "png_to_svg", "PNG to SVG", "trace", "image-x-generic-symbolic", (const char*[]){ "png", "svg", "images", NULL }, "png2svg", NULL },
    { "image_to_base64", "Image to Base64", "Image to Base64", "image-x-generic-symbolic", (const char*[]){ "image", "base64", "images", NULL }, "image2base64", NULL },
    { "image_compression", "Image Compression", "Image Compression", "image-x-generic-symbolic", (const char*[]){ "compression", "image", "images", NULL }, "image-compression", NULL },
    { "lossless_optimizer", "Lossless Optimizer", "Lossless Optimizer", "image-x-generic-symbolic", (const char*[]){ "lossless", "images", "optimizer", NULL }, "lossless-optimizer", NULL },
    { NULL }
};

static const HelvetiaTool tools_special[] = {
    { "qr_code_reader", "QR Code Reader", "QR Code Reader", "image-x-generic-symbolic", (const char*[]){ "reader", "images", "code", NULL }, "qr-code-reader", NULL },
    { "barcode_reader", "Barcode Reader", "Barcode Reader", "image-x-generic-symbolic", (const char*[]){ "barcode", "reader", "images", NULL }, "barcode-reader", NULL },
    { "steganography", "Steganography", "hide/extract text", "image-x-generic-symbolic", (const char*[]){ "images", "steganography", NULL }, "steganography", NULL },
    { "image_to_ascii_art", "Image to ASCII Art", "Image to ASCII Art", "image-x-generic-symbolic", (const char*[]){ "ascii", "art", "image", "images", NULL }, "image2ascii-art", NULL },
    { "pixel_art_scaler", "Pixel Art Scaler", "Pixel Art Scaler", "image-x-generic-symbolic", (const char*[]){ "scaler", "art", "images", "pixel", NULL }, "pixel-art-scaler", NULL },
    { "sprite_sheet_slicer", "Sprite Sheet Slicer", "Sprite Sheet Slicer", "image-x-generic-symbolic", (const char*[]){ "slicer", "sprite", "images", "sheet", NULL }, "sprite-sheet-slicer", NULL },
    { "animated_gif_maker", "Animated GIF Maker", "Animated GIF Maker", "image-x-generic-symbolic", (const char*[]){ "gif", "maker", "animated", "images", NULL }, "animated-gif-maker", NULL },
    { "animated_gif_splitter", "Animated GIF Splitter", "Animated GIF Splitter", "image-x-generic-symbolic", (const char*[]){ "splitter", "gif", "animated", "images", NULL }, "animated-gif-splitter", NULL },
    { "screenshot_tool", "Screenshot Tool", "Screenshot Tool", "image-x-generic-symbolic", (const char*[]){ "screenshot", "tool", "images", NULL }, "screenshot-tool", NULL },
    { "screen_recorder", "Screen Recorder", "GIF/video", "image-x-generic-symbolic", (const char*[]){ "recorder", "images", "screen", NULL }, "screen-recorder", NULL },
    { NULL }
};

static const HelvetiaSubcategory images_subcategories[] = {
    { "Viewing", tools_viewing },
    { "Basic Editing", tools_basic_editing },
    { "Adjustments", tools_adjustments },
    { "Filters", tools_filters },
    { "Drawing & Compositing", tools_drawing_compositing },
    { "Transform", tools_transform },
    { "Retouching", tools_retouching },
    { "Composition", tools_composition },
    { "Format & Conversion", tools_format_conversion },
    { "Special", tools_special },
    { NULL, NULL }
};

static const HelvetiaModule images_module = {
    .id            = "images",
    .name          = "Images",
    .icon_name     = "image-x-generic-symbolic",
    .description   = "From quick crops to full editing.",
    .subcategories = images_subcategories,
    .create_view   = NULL,
    .on_activate   = NULL,
    .on_deactivate = NULL,
    .on_shutdown   = NULL,
};

const HelvetiaModule *helvetia_images_get_module(void) {
    return &images_module;
}
