/* ================================================================
 * Helvetia — PDF Module
 * Auto-generated by gen_modules.py
 * ================================================================ */
#include "pdf_module.h"
#include <stddef.h>

static const HelvetiaTool tools_viewing_navigation[] = {
    { "pdf_viewer", "PDF Viewer", "PDF Viewer", "application-pdf-symbolic", (const char*[]){ "viewer", "pdf", NULL }, "pdf-viewer", NULL },
    { "page_thumbnails", "Page Thumbnails", "Page Thumbnails", "application-pdf-symbolic", (const char*[]){ "pdf", "page", "thumbnails", NULL }, "page-thumbnails", NULL },
    { "pdf_search", "PDF Search", "PDF Search", "system-search-symbolic", (const char*[]){ "search", "pdf", NULL }, "pdf-search", NULL },
    { "pdf_outline_bookmarks", "PDF Outline / Bookmarks", "PDF Outline / Bookmarks", "application-pdf-symbolic", (const char*[]){ "bookmarks", "outline", "pdf", NULL }, "pdf-outline-bookmarks", NULL },
    { "pdf_metadata_viewer", "PDF Metadata Viewer", "PDF Metadata Viewer", "application-pdf-symbolic", (const char*[]){ "viewer", "metadata", "pdf", NULL }, "pdf-metadata-viewer", NULL },
    { NULL }
};

static const HelvetiaTool tools_organizing[] = {
    { "merge_pdfs", "Merge PDFs", "Merge PDFs", "list-add-symbolic", (const char*[]){ "pdfs", "merge", "pdf", NULL }, "merge-pdfs", build_pdf_merge },
    { "split_pdf", "Split PDF", "Split PDF", "list-remove-symbolic", (const char*[]){ "split", "pdf", NULL }, "split-pdf", build_pdf_split },
    { "extract_pages", "Extract Pages", "Extract Pages", "application-pdf-symbolic", (const char*[]){ "extract", "pages", "pdf", NULL }, "extract-pages", NULL },
    { "delete_pages", "Delete Pages", "Delete Pages", "application-pdf-symbolic", (const char*[]){ "pages", "delete", "pdf", NULL }, "delete-pages", NULL },
    { "reorder_pages", "Reorder Pages", "Reorder Pages", "application-pdf-symbolic", (const char*[]){ "pages", "pdf", "reorder", NULL }, "reorder-pages", NULL },
    { "rotate_pages", "Rotate Pages", "Rotate Pages", "application-pdf-symbolic", (const char*[]){ "pages", "rotate", "pdf", NULL }, "rotate-pages", NULL },
    { "insert_pages", "Insert Pages", "Insert Pages", "application-pdf-symbolic", (const char*[]){ "insert", "pages", "pdf", NULL }, "insert-pages", NULL },
    { "duplicate_pages", "Duplicate Pages", "Duplicate Pages", "application-pdf-symbolic", (const char*[]){ "pages", "pdf", "duplicate", NULL }, "duplicate-pages", NULL },
    { "reverse_page_order", "Reverse Page Order", "Reverse Page Order", "application-pdf-symbolic", (const char*[]){ "pdf", "page", "reverse", "order", NULL }, "reverse-page-order", NULL },
    { NULL }
};

static const HelvetiaTool tools_editing[] = {
    { "pdf_text_editor", "PDF Text Editor", "inline editing", "document-edit-symbolic", (const char*[]){ "editor", "text", "pdf", NULL }, "pdf-text-editor", NULL },
    { "pdf_annotation", "PDF Annotation", "highlight, underline, strike, notes", "document-edit-symbolic", (const char*[]){ "annotation", "pdf", NULL }, "pdf-annotation", NULL },
    { "pdf_drawing", "PDF Drawing", "freehand, shapes, arrows", "application-pdf-symbolic", (const char*[]){ "drawing", "pdf", NULL }, "pdf-drawing", NULL },
    { "pdf_form_filler", "PDF Form Filler", "PDF Form Filler", "application-pdf-symbolic", (const char*[]){ "filler", "form", "pdf", NULL }, "pdf-form-filler", NULL },
    { "pdf_form_creator", "PDF Form Creator", "PDF Form Creator", "application-pdf-symbolic", (const char*[]){ "creator", "form", "pdf", NULL }, "pdf-form-creator", NULL },
    { "pdf_redaction", "PDF Redaction", "PDF Redaction", "application-pdf-symbolic", (const char*[]){ "redaction", "pdf", NULL }, "pdf-redaction", NULL },
    { "pdf_watermark", "PDF Watermark", "text and image", "application-pdf-symbolic", (const char*[]){ "pdf", "watermark", NULL }, "pdf-watermark", NULL },
    { "pdf_page_numbers", "PDF Page Numbers", "PDF Page Numbers", "application-pdf-symbolic", (const char*[]){ "page", "pdf", "numbers", NULL }, "pdf-page-numbers", NULL },
    { "pdf_headers_footers", "PDF Headers & Footers", "PDF Headers & Footers", "application-pdf-symbolic", (const char*[]){ "footers", "pdf", "headers", NULL }, "pdf-headers-footers", NULL },
    { "pdf_stamp_tool", "PDF Stamp Tool", "PDF Stamp Tool", "application-pdf-symbolic", (const char*[]){ "tool", "stamp", "pdf", NULL }, "pdf-stamp-tool", NULL },
    { "pdf_signature", "PDF Signature", "draw, type, image", "application-pdf-symbolic", (const char*[]){ "signature", "pdf", NULL }, "pdf-signature", NULL },
    { "pdf_bookmark_editor", "PDF Bookmark Editor", "PDF Bookmark Editor", "document-edit-symbolic", (const char*[]){ "editor", "bookmark", "pdf", NULL }, "pdf-bookmark-editor", NULL },
    { "pdf_link_editor", "PDF Link Editor", "PDF Link Editor", "document-edit-symbolic", (const char*[]){ "link", "editor", "pdf", NULL }, "pdf-link-editor", NULL },
    { "pdf_attachment_manager", "PDF Attachment Manager", "PDF Attachment Manager", "application-pdf-symbolic", (const char*[]){ "manager", "attachment", "pdf", NULL }, "pdf-attachment-manager", NULL },
    { NULL }
};

static const HelvetiaTool tools_security[] = {
    { "pdf_encrypt", "PDF Encrypt", "password", "dialog-password-symbolic", (const char*[]){ "pdf", "encrypt", NULL }, "pdf-encrypt", NULL },
    { "pdf_decrypt", "PDF Decrypt", "PDF Decrypt", "application-pdf-symbolic", (const char*[]){ "decrypt", "pdf", NULL }, "pdf-decrypt", NULL },
    { "pdf_permissions", "PDF Permissions", "print, copy, edit", "application-pdf-symbolic", (const char*[]){ "permissions", "pdf", NULL }, "pdf-permissions", NULL },
    { "pdf_certificate_sign", "PDF Certificate Sign", "PDF Certificate Sign", "application-pdf-symbolic", (const char*[]){ "sign", "certificate", "pdf", NULL }, "pdf-certificate-sign", NULL },
    { "pdf_timestamp", "PDF Timestamp", "PDF Timestamp", "application-pdf-symbolic", (const char*[]){ "timestamp", "pdf", NULL }, "pdf-timestamp", NULL },
    { NULL }
};

static const HelvetiaTool tools_optimization[] = {
    { "pdf_compress", "PDF Compress", "PDF Compress", "application-pdf-symbolic", (const char*[]){ "compress", "pdf", NULL }, "pdf-compress", NULL },
    { "pdf_optimize_for_web", "PDF Optimize for Web", "PDF Optimize for Web", "application-pdf-symbolic", (const char*[]){ "web", "for", "pdf", "optimize", NULL }, "pdf-optimize-for-web", NULL },
    { "pdf_optimize_for_print", "PDF Optimize for Print", "PDF Optimize for Print", "printer-symbolic", (const char*[]){ "for", "print", "pdf", "optimize", NULL }, "pdf-optimize-for-print", NULL },
    { "pdf_repair", "PDF Repair", "PDF Repair", "application-pdf-symbolic", (const char*[]){ "pdf", "repair", NULL }, "pdf-repair", NULL },
    { "pdf_linearize", "PDF Linearize", "fast web view", "application-pdf-symbolic", (const char*[]){ "pdf", "linearize", NULL }, "pdf-linearize", NULL },
    { NULL }
};

static const HelvetiaTool tools_conversion[] = {
    { "pdf_to_image", "PDF to Image", "PNG, JPG, TIFF, WEBP", "application-pdf-symbolic", (const char*[]){ "image", "pdf", NULL }, "pdf2image", build_pdf_to_image },
    { "image_to_pdf", "Image to PDF", "Image to PDF", "application-pdf-symbolic", (const char*[]){ "image", "pdf", NULL }, "image2pdf", NULL },
    { "pdf_to_text", "PDF to Text", "PDF to Text", "application-pdf-symbolic", (const char*[]){ "text", "pdf", NULL }, "pdf2text", build_pdf_to_text },
    { "pdf_to_html", "PDF to HTML", "PDF to HTML", "application-pdf-symbolic", (const char*[]){ "html", "pdf", NULL }, "pdf2html", NULL },
    { "pdf_to_docx", "PDF to DOCX", "PDF to DOCX", "application-pdf-symbolic", (const char*[]){ "docx", "pdf", NULL }, "pdf2docx", NULL },
    { "pdf_to_xlsx", "PDF to XLSX", "PDF to XLSX", "application-pdf-symbolic", (const char*[]){ "xlsx", "pdf", NULL }, "pdf2xlsx", NULL },
    { "pdf_to_pptx", "PDF to PPTX", "PDF to PPTX", "application-pdf-symbolic", (const char*[]){ "pptx", "pdf", NULL }, "pdf2pptx", NULL },
    { "pdf_to_markdown", "PDF to Markdown", "PDF to Markdown", "application-pdf-symbolic", (const char*[]){ "markdown", "pdf", NULL }, "pdf2markdown", NULL },
    { "pdf_to_epub", "PDF to EPUB", "PDF to EPUB", "application-pdf-symbolic", (const char*[]){ "epub", "pdf", NULL }, "pdf2epub", NULL },
    { "office_to_pdf", "Office to PDF", "DOCX, XLSX, PPTX, ODT, ODS", "application-pdf-symbolic", (const char*[]){ "pdf", "office", NULL }, "office2pdf", NULL },
    { "html_to_pdf", "HTML to PDF", "HTML to PDF", "application-pdf-symbolic", (const char*[]){ "html", "pdf", NULL }, "html2pdf", NULL },
    { "markdown_to_pdf", "Markdown to PDF", "Markdown to PDF", "application-pdf-symbolic", (const char*[]){ "markdown", "pdf", NULL }, "markdown2pdf", NULL },
    { "epub_to_pdf", "EPUB to PDF", "EPUB to PDF", "application-pdf-symbolic", (const char*[]){ "epub", "pdf", NULL }, "epub2pdf", NULL },
    { "pdf_a_converter", "PDF/A Converter", "archival", "application-pdf-symbolic", (const char*[]){ "converter", "pdfa", "pdf", NULL }, "pdf-a-converter", NULL },
    { NULL }
};

static const HelvetiaTool tools_ocr_scan[] = {
    { "ocr_pdf", "OCR PDF", "Tesseract", "application-pdf-symbolic", (const char*[]){ "ocr", "pdf", NULL }, "ocr-pdf", NULL },
    { "ocr_image_to_text", "OCR Image to Text", "OCR Image to Text", "application-pdf-symbolic", (const char*[]){ "ocr", "image", "text", "pdf", NULL }, "ocr-image2text", NULL },
    { "scan_to_pdf", "Scan to PDF", "SANE scanner", "application-pdf-symbolic", (const char*[]){ "scan", "pdf", NULL }, "scan2pdf", NULL },
    { "multi_page_scan", "Multi-page Scan", "Multi-page Scan", "application-pdf-symbolic", (const char*[]){ "multipage", "pdf", "scan", NULL }, "multi-page-scan", NULL },
    { "deskew_scanned_pages", "Deskew Scanned Pages", "Deskew Scanned Pages", "application-pdf-symbolic", (const char*[]){ "scanned", "pages", "deskew", "pdf", NULL }, "deskew-scanned-pages", NULL },
    { "auto_crop_scan", "Auto-crop Scan", "Auto-crop Scan", "application-pdf-symbolic", (const char*[]){ "autocrop", "scan", "pdf", NULL }, "auto-crop-scan", NULL },
    { NULL }
};

static const HelvetiaTool tools_comparison[] = {
    { "pdf_compare", "PDF Compare", "side-by-side diff", "application-pdf-symbolic", (const char*[]){ "compare", "pdf", NULL }, "pdf-compare", NULL },
    { "pdf_overlay_compare", "PDF Overlay Compare", "PDF Overlay Compare", "application-pdf-symbolic", (const char*[]){ "overlay", "compare", "pdf", NULL }, "pdf-overlay-compare", NULL },
    { NULL }
};

static const HelvetiaSubcategory pdf_subcategories[] = {
    { "Viewing & Navigation", tools_viewing_navigation },
    { "Organizing", tools_organizing },
    { "Editing", tools_editing },
    { "Security", tools_security },
    { "Optimization", tools_optimization },
    { "Conversion", tools_conversion },
    { "OCR & Scan", tools_ocr_scan },
    { "Comparison", tools_comparison },
    { NULL, NULL }
};

static const HelvetiaModule pdf_module = {
    .id            = "pdf",
    .name          = "PDF",
    .icon_name     = "application-pdf-symbolic",
    .description   = "Full PDF editing, all offline.",
    .subcategories = pdf_subcategories,
    .create_view   = NULL,
    .on_activate   = NULL,
    .on_deactivate = NULL,
    .on_shutdown   = NULL,
};

const HelvetiaModule *helvetia_pdf_get_module(void) {
    return &pdf_module;
}
