/* ================================================================
 * Helvetia — Dev Tools Module
 * Auto-generated by gen_modules.py
 * ================================================================ */
#include "devtools_module.h"
#include <stddef.h>

static const HelvetiaTool tools_encoding_formats[] = {
    { "base64_tool", "Base64 Tool", "Base64 Tool", "applications-development-symbolic", (const char*[]){ "devtools", "base64", "tool", NULL }, "base64-tool", NULL },
    { "url_encoder", "URL Encoder", "URL Encoder", "applications-development-symbolic", (const char*[]){ "devtools", "encoder", "url", NULL }, "url-encoder", NULL },
    { "jwt_decoder", "JWT Decoder", "JWT Decoder", "applications-development-symbolic", (const char*[]){ "devtools", "jwt", "decoder", NULL }, "jwt-decoder", build_jwt_decoder },
    { "jwt_encoder", "JWT Encoder", "JWT Encoder", "applications-development-symbolic", (const char*[]){ "devtools", "encoder", "jwt", NULL }, "jwt-encoder", NULL },
    { "uuid_ulid_nanoid_generator", "UUID / ULID / NanoID Generator", "UUID / ULID / NanoID Generator", "applications-development-symbolic", (const char*[]){ "generator", "nanoid", "devtools", "uuid", "ulid", NULL }, "uuid-ulid-nanoid-generator", NULL },
    { "hash_tool", "Hash Tool", "Hash Tool", "applications-development-symbolic", (const char*[]){ "devtools", "hash", "tool", NULL }, "hash-tool", NULL },
    { "hmac_tool", "HMAC Tool", "HMAC Tool", "applications-development-symbolic", (const char*[]){ "hmac", "devtools", "tool", NULL }, "hmac-tool", NULL },
    { "bcrypt_argon2_tool", "Bcrypt / Argon2 Tool", "Bcrypt / Argon2 Tool", "applications-development-symbolic", (const char*[]){ "bcrypt", "devtools", "tool", "argon2", NULL }, "bcrypt-argon2-tool", NULL },
    { NULL }
};

static const HelvetiaTool tools_data[] = {
    { "json_formatter", "JSON Formatter", "JSON Formatter", "text-x-script-symbolic", (const char*[]){ "json", "devtools", "formatter", NULL }, "json-formatter", NULL },
    { "json_validator", "JSON Validator", "JSON Validator", "text-x-script-symbolic", (const char*[]){ "validator", "json", "devtools", NULL }, "json-validator", NULL },
    { "jsonpath_tester", "JSONPath Tester", "JSONPath Tester", "text-x-script-symbolic", (const char*[]){ "jsonpath", "tester", "devtools", NULL }, "jsonpath-tester", NULL },
    { "json_diff", "JSON Diff", "JSON Diff", "text-x-script-symbolic", (const char*[]){ "json", "devtools", "diff", NULL }, "json-diff", NULL },
    { "yaml_formatter", "YAML Formatter", "YAML Formatter", "applications-development-symbolic", (const char*[]){ "devtools", "yaml", "formatter", NULL }, "yaml-formatter", NULL },
    { "xml_formatter", "XML Formatter", "XML Formatter", "text-x-script-symbolic", (const char*[]){ "devtools", "xml", "formatter", NULL }, "xml-formatter", NULL },
    { "toml_formatter", "TOML Formatter", "TOML Formatter", "applications-development-symbolic", (const char*[]){ "toml", "devtools", "formatter", NULL }, "toml-formatter", NULL },
    { "sql_formatter", "SQL Formatter", "SQL Formatter", "applications-development-symbolic", (const char*[]){ "devtools", "sql", "formatter", NULL }, "sql-formatter", NULL },
    { "csv_formatter", "CSV Formatter", "CSV Formatter", "applications-development-symbolic", (const char*[]){ "devtools", "csv", "formatter", NULL }, "csv-formatter", NULL },
    { NULL }
};

static const HelvetiaTool tools_text_regex[] = {
    { "regex_tester", "Regex Tester", "Regex Tester", "system-search-symbolic", (const char*[]){ "tester", "devtools", "regex", NULL }, "regex-tester", NULL },
    { "regex_cheatsheet", "Regex Cheatsheet", "Regex Cheatsheet", "system-search-symbolic", (const char*[]){ "devtools", "regex", "cheatsheet", NULL }, "regex-cheatsheet", NULL },
    { "text_diff", "Text Diff", "Text Diff", "applications-development-symbolic", (const char*[]){ "devtools", "text", "diff", NULL }, "text-diff", NULL },
    { "line_sorter_deduplicator", "Line Sorter / Deduplicator", "Line Sorter / Deduplicator", "applications-development-symbolic", (const char*[]){ "line", "sorter", "devtools", "deduplicator", NULL }, "line-sorter-deduplicator", NULL },
    { "case_converter", "Case Converter", "Case Converter", "applications-development-symbolic", (const char*[]){ "case", "devtools", "converter", NULL }, "case-converter", NULL },
    { "slug_generator", "Slug Generator", "Slug Generator", "applications-development-symbolic", (const char*[]){ "generator", "slug", "devtools", NULL }, "slug-generator", NULL },
    { "string_escape_unescape", "String Escape / Unescape", "String Escape / Unescape", "applications-development-symbolic", (const char*[]){ "unescape", "string", "devtools", "escape", NULL }, "string-escape-unescape", NULL },
    { "lorem_ipsum", "Lorem Ipsum", "Lorem Ipsum", "network-wired-symbolic", (const char*[]){ "ipsum", "devtools", "lorem", NULL }, "lorem-ipsum", NULL },
    { NULL }
};

static const HelvetiaTool tools_time_numbers[] = {
    { "unix_timestamp_converter", "Unix Timestamp Converter", "Unix Timestamp Converter", "applications-development-symbolic", (const char*[]){ "converter", "timestamp", "devtools", "unix", NULL }, "unix-timestamp-converter", build_dev_timestamp },
    { "iso_8601_converter", "ISO 8601 Converter", "ISO 8601 Converter", "applications-development-symbolic", (const char*[]){ "iso", "devtools", "converter", "8601", NULL }, "iso-8601-converter", NULL },
    { "cron_parser", "Cron Parser", "Cron Parser", "applications-development-symbolic", (const char*[]){ "parser", "devtools", "cron", NULL }, "cron-parser", NULL },
    { "number_base_converter", "Number Base Converter", "Number Base Converter", "applications-development-symbolic", (const char*[]){ "devtools", "converter", "base", "number", NULL }, "number-base-converter", build_number_base_dev },
    { "bitwise_calculator", "Bitwise Calculator", "Bitwise Calculator", "applications-development-symbolic", (const char*[]){ "calculator", "devtools", "bitwise", NULL }, "bitwise-calculator", NULL },
    { "byte_size_converter", "Byte Size Converter", "Byte Size Converter", "applications-development-symbolic", (const char*[]){ "devtools", "byte", "converter", "size", NULL }, "byte-size-converter", NULL },
    { "random_data_generator", "Random Data Generator", "Random Data Generator", "applications-development-symbolic", (const char*[]){ "generator", "random", "devtools", "data", NULL }, "random-data-generator", NULL },
    { NULL }
};

static const HelvetiaTool tools_network_web[] = {
    { "http_header_parser", "HTTP Header Parser", "HTTP Header Parser", "applications-development-symbolic", (const char*[]){ "http", "parser", "header", "devtools", NULL }, "http-header-parser", NULL },
    { "url_parser", "URL Parser", "URL Parser", "applications-development-symbolic", (const char*[]){ "parser", "devtools", "url", NULL }, "url-parser", NULL },
    { "user_agent_parser", "User-Agent Parser", "User-Agent Parser", "applications-development-symbolic", (const char*[]){ "parser", "useragent", "devtools", NULL }, "user-agent-parser", NULL },
    { "mime_type_lookup", "MIME Type Lookup", "MIME Type Lookup", "applications-development-symbolic", (const char*[]){ "type", "devtools", "mime", "lookup", NULL }, "mime-type-lookup", NULL },
    { "http_status_code_lookup", "HTTP Status Code Lookup", "HTTP Status Code Lookup", "applications-development-symbolic", (const char*[]){ "http", "devtools", "code", "lookup", "status", NULL }, "http-status-code-lookup", build_http_status_lookup },
    { "cidr_calculator", "CIDR Calculator", "CIDR Calculator", "applications-development-symbolic", (const char*[]){ "calculator", "cidr", "devtools", NULL }, "cidr-calculator", NULL },
    { "ipv4_ipv6_converter", "IPv4 / IPv6 Converter", "IPv4 / IPv6 Converter", "network-wired-symbolic", (const char*[]){ "ipv4", "ipv6", "devtools", "converter", NULL }, "ipv4-ipv6-converter", NULL },
    { NULL }
};

static const HelvetiaTool tools_code_files[] = {
    { "code_formatter", "Code Formatter", "C, Python, JS, JSON, XML, SQL, etc.", "applications-development-symbolic", (const char*[]){ "devtools", "code", "formatter", NULL }, "code-formatter", NULL },
    { "code_minifier", "Code Minifier", "Code Minifier", "applications-development-symbolic", (const char*[]){ "minifier", "code", "devtools", NULL }, "code-minifier", NULL },
    { "diff_viewer", "Diff Viewer", "Diff Viewer", "applications-development-symbolic", (const char*[]){ "devtools", "viewer", "diff", NULL }, "diff-viewer", NULL },
    { "file_type_detector", "File Type Detector", "File Type Detector", "applications-development-symbolic", (const char*[]){ "type", "detector", "devtools", "file", NULL }, "file-type-detector", NULL },
    { "hex_viewer", "Hex Viewer", "Hex Viewer", "applications-development-symbolic", (const char*[]){ "hex", "devtools", "viewer", NULL }, "hex-viewer", build_hex_viewer },
    { "binary_viewer", "Binary Viewer", "Binary Viewer", "applications-development-symbolic", (const char*[]){ "binary", "devtools", "viewer", NULL }, "binary-viewer", NULL },
    { "file_checksum", "File Checksum", "File Checksum", "applications-development-symbolic", (const char*[]){ "checksum", "devtools", "file", NULL }, "file-checksum", NULL },
    { "line_ending_converter", "Line Ending Converter", "Line Ending Converter", "applications-development-symbolic", (const char*[]){ "line", "ending", "devtools", "converter", NULL }, "line-ending-converter", NULL },
    { NULL }
};

static const HelvetiaTool tools_generators[] = {
    { "uuid_generator", "UUID Generator", "UUID Generator", "applications-development-symbolic", (const char*[]){ "uuid", "generator", "devtools", NULL }, "uuid-generator", build_uuid_generator },
    { "password_generator", "Password Generator", "Password Generator", "applications-development-symbolic", (const char*[]){ "generator", "devtools", "password", NULL }, "password-generator", NULL },
    { "lorem_ipsum_generator", "Lorem Ipsum Generator", "Lorem Ipsum Generator", "network-wired-symbolic", (const char*[]){ "ipsum", "generator", "lorem", "devtools", NULL }, "lorem-ipsum-generator", NULL },
    { "dummy_json_generator", "Dummy JSON Generator", "Dummy JSON Generator", "text-x-script-symbolic", (const char*[]){ "generator", "json", "devtools", "dummy", NULL }, "dummy-json-generator", NULL },
    { "fake_data_generator", "Fake Data Generator", "Fake Data Generator", "applications-development-symbolic", (const char*[]){ "generator", "devtools", "fake", "data", NULL }, "fake-data-generator", NULL },
    { "qr_code_generator", "QR Code Generator", "QR Code Generator", "applications-development-symbolic", (const char*[]){ "generator", "devtools", "code", NULL }, "qr-code-generator", NULL },
    { "barcode_generator", "Barcode Generator", "Barcode Generator", "applications-development-symbolic", (const char*[]){ "barcode", "generator", "devtools", NULL }, "barcode-generator", NULL },
    { "color_palette_generator", "Color Palette Generator", "Color Palette Generator", "applications-development-symbolic", (const char*[]){ "color", "generator", "devtools", "palette", NULL }, "color-palette-generator", NULL },
    { NULL }
};

static const HelvetiaTool tools_api_testing[] = {
    { "rest_client", "REST Client", "offline, local only", "applications-development-symbolic", (const char*[]){ "client", "devtools", "rest", NULL }, "rest-client", NULL },
    { "graphql_query_tester", "GraphQL Query Tester", "offline schema", "applications-development-symbolic", (const char*[]){ "graphql", "tester", "devtools", "query", NULL }, "graphql-query-tester", NULL },
    { "websocket_tester", "WebSocket Tester", "local", "applications-development-symbolic", (const char*[]){ "tester", "websocket", "devtools", NULL }, "websocket-tester", NULL },
    { "json_schema_validator", "JSON Schema Validator", "JSON Schema Validator", "text-x-script-symbolic", (const char*[]){ "validator", "json", "schema", "devtools", NULL }, "json-schema-validator", NULL },
    { "openapi_viewer", "OpenAPI Viewer", "OpenAPI Viewer", "applications-development-symbolic", (const char*[]){ "devtools", "viewer", "openapi", NULL }, "openapi-viewer", NULL },
    { NULL }
};

static const HelvetiaTool tools_system_info[] = {
    { "system_info_viewer", "System Info Viewer", "System Info Viewer", "applications-development-symbolic", (const char*[]){ "devtools", "info", "viewer", "system", NULL }, "system-info-viewer", NULL },
    { "disk_usage_viewer", "Disk Usage Viewer", "Disk Usage Viewer", "applications-development-symbolic", (const char*[]){ "usage", "devtools", "viewer", "disk", NULL }, "disk-usage-viewer", NULL },
    { "process_viewer", "Process Viewer", "Process Viewer", "applications-development-symbolic", (const char*[]){ "process", "devtools", "viewer", NULL }, "process-viewer", NULL },
    { "environment_variable_viewer", "Environment Variable Viewer", "Environment Variable Viewer", "applications-development-symbolic", (const char*[]){ "variable", "devtools", "viewer", "environment", NULL }, "environment-variable-viewer", NULL },
    { "font_viewer", "Font Viewer", "Font Viewer", "applications-development-symbolic", (const char*[]){ "devtools", "viewer", "font", NULL }, "font-viewer", NULL },
    { "installed_package_viewer", "Installed Package Viewer", "Installed Package Viewer", "applications-development-symbolic", (const char*[]){ "devtools", "package", "installed", "viewer", NULL }, "installed-package-viewer", NULL },
    { "network_interface_viewer", "Network Interface Viewer", "Network Interface Viewer", "network-wired-symbolic", (const char*[]){ "interface", "devtools", "viewer", "network", NULL }, "network-interface-viewer", NULL },
    { "battery_info", "Battery Info", "Battery Info", "applications-development-symbolic", (const char*[]){ "info", "battery", "devtools", NULL }, "battery-info", NULL },
    { "cpu_memory_monitor", "CPU / Memory Monitor", "CPU / Memory Monitor", "applications-development-symbolic", (const char*[]){ "cpu", "devtools", "monitor", "memory", NULL }, "cpu-memory-monitor", NULL },
    { "sensors_viewer", "Sensors Viewer", "Sensors Viewer", "applications-development-symbolic", (const char*[]){ "devtools", "sensors", "viewer", NULL }, "sensors-viewer", NULL },
    { NULL }
};

static const HelvetiaSubcategory devtools_subcategories[] = {
    { "Encoding & Formats", tools_encoding_formats },
    { "Data", tools_data },
    { "Text & Regex", tools_text_regex },
    { "Time & Numbers", tools_time_numbers },
    { "Network & Web", tools_network_web },
    { "Code & Files", tools_code_files },
    { "Generators", tools_generators },
    { "API & Testing", tools_api_testing },
    { "System Info", tools_system_info },
    { NULL, NULL }
};

static const HelvetiaModule devtools_module = {
    .id            = "devtools",
    .name          = "Dev Tools",
    .icon_name     = "applications-development-symbolic",
    .description   = "Everyday developer utilities.",
    .subcategories = devtools_subcategories,
    .create_view   = NULL,
    .on_activate   = NULL,
    .on_deactivate = NULL,
    .on_shutdown   = NULL,
};

const HelvetiaModule *helvetia_devtools_get_module(void) {
    return &devtools_module;
}
