/* ================================================================
 * Helvetia — Convert Module
 * Auto-generated by gen_modules.py
 * ================================================================ */
#include "convert_module.h"
#include <stddef.h>

static const HelvetiaTool tools_archives[] = {
    { "zip_create", "ZIP Create", "ZIP Create", "package-x-generic-symbolic", (const char*[]){ "convert", "create", "zip", NULL }, "zip-create", NULL },
    { "zip_extract", "ZIP Extract", "ZIP Extract", "package-x-generic-symbolic", (const char*[]){ "extract", "convert", "zip", NULL }, "zip-extract", NULL },
    { "tar_create_extract", "TAR Create / Extract", "TAR Create / Extract", "package-x-generic-symbolic", (const char*[]){ "extract", "tar", "create", "convert", NULL }, "tar-create-extract", NULL },
    { "gz_bz2_xz_compress", "GZ / BZ2 / XZ Compress", "GZ / BZ2 / XZ Compress", "view-refresh-symbolic", (const char*[]){ "compress", "convert", "bz2", NULL }, "gz-bz2-xz-compress", NULL },
    { "7z_create_extract", "7Z Create / Extract", "7Z Create / Extract", "view-refresh-symbolic", (const char*[]){ "extract", "convert", "create", NULL }, "7z-create-extract", NULL },
    { "rar_extract", "RAR Extract", "RAR Extract", "view-refresh-symbolic", (const char*[]){ "extract", "convert", "rar", NULL }, "rar-extract", NULL },
    { "archive_converter", "Archive Converter", "Archive Converter", "package-x-generic-symbolic", (const char*[]){ "convert", "converter", "archive", NULL }, "archive-converter", NULL },
    { "archive_splitter", "Archive Splitter", "Archive Splitter", "package-x-generic-symbolic", (const char*[]){ "convert", "splitter", "archive", NULL }, "archive-splitter", NULL },
    { "archive_password", "Archive Password", "Archive Password", "package-x-generic-symbolic", (const char*[]){ "convert", "password", "archive", NULL }, "archive-password", NULL },
    { NULL }
};

static const HelvetiaTool tools_data_formats[] = {
    { "json_formatter", "JSON Formatter", "JSON Formatter", "view-refresh-symbolic", (const char*[]){ "convert", "json", "formatter", NULL }, "json-formatter", build_json_formatter },
    { "json_validator", "JSON Validator", "Validate JSON syntax", "view-refresh-symbolic", (const char*[]){ "validator", "json", "convert", NULL }, "json-validator", build_json_validator },
    { "json_to_yaml", "JSON to YAML", "JSON to YAML", "view-refresh-symbolic", (const char*[]){ "convert", "json", "yaml", NULL }, "json2yaml", NULL },
    { "yaml_to_json", "YAML to JSON", "YAML to JSON", "view-refresh-symbolic", (const char*[]){ "convert", "json", "yaml", NULL }, "yaml2json", NULL },
    { "json_to_xml", "JSON to XML", "JSON to XML", "view-refresh-symbolic", (const char*[]){ "convert", "json", "xml", NULL }, "json2xml", NULL },
    { "xml_to_json", "XML to JSON", "XML to JSON", "view-refresh-symbolic", (const char*[]){ "convert", "json", "xml", NULL }, "xml2json", NULL },
    { "json_to_toml", "JSON to TOML", "JSON to TOML", "view-refresh-symbolic", (const char*[]){ "toml", "convert", "json", NULL }, "json2toml", NULL },
    { "toml_to_json", "TOML to JSON", "TOML to JSON", "view-refresh-symbolic", (const char*[]){ "toml", "convert", "json", NULL }, "toml2json", NULL },
    { "csv_to_json", "CSV to JSON", "CSV to JSON", "view-refresh-symbolic", (const char*[]){ "convert", "json", "csv", NULL }, "csv2json", NULL },
    { "json_to_csv", "JSON to CSV", "JSON to CSV", "view-refresh-symbolic", (const char*[]){ "convert", "json", "csv", NULL }, "json2csv", NULL },
    { "json_to_sql", "JSON to SQL", "JSON to SQL", "view-refresh-symbolic", (const char*[]){ "convert", "json", "sql", NULL }, "json2sql", NULL },
    { "sql_to_json", "SQL to JSON", "SQL to JSON", "view-refresh-symbolic", (const char*[]){ "convert", "json", "sql", NULL }, "sql2json", NULL },
    { "jsonpath_tester", "JSONPath Tester", "JSONPath Tester", "view-refresh-symbolic", (const char*[]){ "jsonpath", "convert", "tester", NULL }, "jsonpath-tester", NULL },
    { "xml_formatter", "XML Formatter", "XML Formatter", "view-refresh-symbolic", (const char*[]){ "convert", "xml", "formatter", NULL }, "xml-formatter", NULL },
    { "xml_to_yaml", "XML to YAML", "XML to YAML", "view-refresh-symbolic", (const char*[]){ "yaml", "convert", "xml", NULL }, "xml2yaml", NULL },
    { NULL }
};

static const HelvetiaTool tools_encoding[] = {
    { "base64_encode", "Base64 Encode", "Base64 Encode", "accessories-character-map-symbolic", (const char*[]){ "convert", "base64", "encode", NULL }, "base64-encode", build_base64_tool },
    { "base64_decode", "Base64 Decode", "Base64 Decode", "accessories-character-map-symbolic", (const char*[]){ "convert", "decode", "base64", NULL }, "base64-decode", build_base64_tool },
    { "url_encode_decode", "URL Encode / Decode", "URL Encode / Decode", "accessories-character-map-symbolic", (const char*[]){ "convert", "encode", "decode", "url", NULL }, "url-encode-decode", build_url_encoder },
    { "html_entity_encode_decode", "HTML Entity Encode / Decode", "HTML Entity Encode / Decode", "accessories-character-map-symbolic", (const char*[]){ "convert", "decode", "html", "entity", "encode", NULL }, "html-entity-encode-decode", NULL },
    { "hex_encode_decode", "Hex Encode / Decode", "Hex Encode / Decode", "accessories-character-map-symbolic", (const char*[]){ "convert", "hex", "decode", "encode", NULL }, "hex-encode-decode", build_hex_encoder },
    { "binary_encode_decode", "Binary Encode / Decode", "Binary Encode / Decode", "accessories-character-map-symbolic", (const char*[]){ "binary", "convert", "decode", "encode", NULL }, "binary-encode-decode", NULL },
    { "unicode_escape_unescape", "Unicode Escape / Unescape", "Unicode Escape / Unescape", "accessories-character-map-symbolic", (const char*[]){ "unicode", "convert", "unescape", "escape", NULL }, "unicode-escape-unescape", NULL },
    { "rot13", "ROT13", "ROT13", "view-refresh-symbolic", (const char*[]){ "rot13", "convert", NULL }, "rot13", build_rot13 },
    { "morse_code", "Morse Code", "Morse Code", "accessories-character-map-symbolic", (const char*[]){ "convert", "code", "morse", NULL }, "morse-code", NULL },
    { "nato_alphabet", "NATO Alphabet", "NATO Alphabet", "view-refresh-symbolic", (const char*[]){ "nato", "convert", "alphabet", NULL }, "nato-alphabet", NULL },
    { NULL }
};

static const HelvetiaTool tools_charset[] = {
    { "character_encoding_converter", "Character Encoding Converter", "UTF-8, UTF-16, ISO-8859, Shift-JIS, GBK, KOI8", "view-refresh-symbolic", (const char*[]){ "convert", "encoding", "converter", "character", NULL }, "character-encoding-converter", NULL },
    { "line_ending_converter", "Line Ending Converter", "LF, CRLF, CR", "view-refresh-symbolic", (const char*[]){ "line", "convert", "ending", "converter", NULL }, "line-ending-converter", build_line_ending_converter },
    { "bom_add_remove", "BOM Add / Remove", "BOM Add / Remove", "view-refresh-symbolic", (const char*[]){ "remove", "convert", "add", "bom", NULL }, "bom-add-remove", NULL },
    { NULL }
};

static const HelvetiaTool tools_universal[] = {
    { "universal_file_converter", "Universal File Converter", "any → any supported", "view-refresh-symbolic", (const char*[]){ "universal", "convert", "converter", "file", NULL }, "universal-file-converter", NULL },
    { "batch_converter", "Batch Converter", "Batch Converter", "view-refresh-symbolic", (const char*[]){ "batch", "convert", "converter", NULL }, "batch-converter", NULL },
    { "file_format_inspector", "File Format Inspector", "File Format Inspector", "view-refresh-symbolic", (const char*[]){ "format", "convert", "inspector", "file", NULL }, "file-format-inspector", NULL },
    { "file_type_detector", "File Type Detector", "libmagic", "view-refresh-symbolic", (const char*[]){ "type", "detector", "convert", "file", NULL }, "file-type-detector", build_file_type_detector },
    { "file_splitter_joiner", "File Splitter / Joiner", "File Splitter / Joiner", "view-refresh-symbolic", (const char*[]){ "joiner", "splitter", "convert", "file", NULL }, "file-splitter-joiner", NULL },
    { "file_renamer", "File Renamer", "batch, regex", "view-refresh-symbolic", (const char*[]){ "convert", "file", "renamer", NULL }, "file-renamer", NULL },
    { "file_timestamp_editor", "File Timestamp Editor", "File Timestamp Editor", "view-refresh-symbolic", (const char*[]){ "convert", "editor", "timestamp", "file", NULL }, "file-timestamp-editor", NULL },
    { "file_permission_editor", "File Permission Editor", "File Permission Editor", "view-refresh-symbolic", (const char*[]){ "convert", "permission", "editor", "file", NULL }, "file-permission-editor", NULL },
    { NULL }
};

static const HelvetiaSubcategory convert_subcategories[] = {
    { "Archives", tools_archives },
    { "Data Formats", tools_data_formats },
    { "Encoding", tools_encoding },
    { "Charset", tools_charset },
    { "Universal", tools_universal },
    { NULL, NULL }
};

static const HelvetiaModule convert_module = {
    .id            = "convert",
    .name          = "Convert",
    .icon_name     = "view-refresh-symbolic",
    .description   = "Universal file format conversion.",
    .subcategories = convert_subcategories,
    .create_view   = NULL,
    .on_activate   = NULL,
    .on_deactivate = NULL,
    .on_shutdown   = NULL,
};

const HelvetiaModule *helvetia_convert_get_module(void) {
    return &convert_module;
}
