/* ================================================================
 * Helvetia — Media Module
 * Auto-generated by gen_modules.py
 * ================================================================ */
#include "media_module.h"
#include <stddef.h>

static const HelvetiaTool tools_audio[] = {
    { "audio_player", "Audio Player", "Audio Player", "audio-x-generic-symbolic", (const char*[]){ "player", "media", "audio", NULL }, "audio-player", NULL },
    { "audio_converter", "Audio Converter", "MP3, FLAC, WAV, OGG, AAC, OPUS, M4A", "audio-x-generic-symbolic", (const char*[]){ "media", "converter", "audio", NULL }, "audio-converter", NULL },
    { "audio_trimmer", "Audio Trimmer", "Audio Trimmer", "audio-x-generic-symbolic", (const char*[]){ "media", "trimmer", "audio", NULL }, "audio-trimmer", NULL },
    { "audio_merger", "Audio Merger", "Audio Merger", "audio-x-generic-symbolic", (const char*[]){ "merger", "media", "audio", NULL }, "audio-merger", NULL },
    { "audio_splitter", "Audio Splitter", "Audio Splitter", "audio-x-generic-symbolic", (const char*[]){ "splitter", "media", "audio", NULL }, "audio-splitter", NULL },
    { "audio_normalizer", "Audio Normalizer", "Audio Normalizer", "audio-x-generic-symbolic", (const char*[]){ "media", "normalizer", "audio", NULL }, "audio-normalizer", NULL },
    { "audio_compressor", "Audio Compressor", "Audio Compressor", "audio-x-generic-symbolic", (const char*[]){ "compressor", "media", "audio", NULL }, "audio-compressor", NULL },
    { "audio_amplifier", "Audio Amplifier", "Audio Amplifier", "audio-x-generic-symbolic", (const char*[]){ "media", "amplifier", "audio", NULL }, "audio-amplifier", NULL },
    { "audio_fade_in_out", "Audio Fade In/Out", "Audio Fade In/Out", "audio-x-generic-symbolic", (const char*[]){ "media", "inout", "audio", "fade", NULL }, "audio-fade-in-out", NULL },
    { "audio_pitch_shift", "Audio Pitch Shift", "Audio Pitch Shift", "audio-x-generic-symbolic", (const char*[]){ "media", "pitch", "audio", "shift", NULL }, "audio-pitch-shift", NULL },
    { "audio_speed_change", "Audio Speed Change", "Audio Speed Change", "audio-x-generic-symbolic", (const char*[]){ "change", "media", "speed", "audio", NULL }, "audio-speed-change", NULL },
    { "audio_reverb", "Audio Reverb", "Audio Reverb", "audio-x-generic-symbolic", (const char*[]){ "reverb", "media", "audio", NULL }, "audio-reverb", NULL },
    { "audio_equalizer", "Audio Equalizer", "Audio Equalizer", "audio-x-generic-symbolic", (const char*[]){ "media", "equalizer", "audio", NULL }, "audio-equalizer", NULL },
    { "audio_noise_removal", "Audio Noise Removal", "Audio Noise Removal", "audio-x-generic-symbolic", (const char*[]){ "removal", "media", "noise", "audio", NULL }, "audio-noise-removal", NULL },
    { "audio_metadata_editor", "Audio Metadata Editor", "Audio Metadata Editor", "audio-x-generic-symbolic", (const char*[]){ "media", "editor", "metadata", "audio", NULL }, "audio-metadata-editor", NULL },
    { "audio_waveform_viewer", "Audio Waveform Viewer", "Audio Waveform Viewer", "audio-x-generic-symbolic", (const char*[]){ "media", "waveform", "viewer", "audio", NULL }, "audio-waveform-viewer", NULL },
    { "audio_spectrogram", "Audio Spectrogram", "Audio Spectrogram", "audio-x-generic-symbolic", (const char*[]){ "spectrogram", "media", "audio", NULL }, "audio-spectrogram", NULL },
    { "text_to_speech", "Text to Speech", "eSpeak NG / Piper", "multimedia-video-player-symbolic", (const char*[]){ "speech", "media", "text", NULL }, "text2speech", NULL },
    { "speech_to_text", "Speech to Text", "Whisper.cpp", "multimedia-video-player-symbolic", (const char*[]){ "speech", "media", "text", NULL }, "speech2text", NULL },
    { "audio_transcription", "Audio Transcription", "Audio Transcription", "audio-x-generic-symbolic", (const char*[]){ "media", "transcription", "audio", NULL }, "audio-transcription", NULL },
    { "audio_chapter_splitter", "Audio Chapter Splitter", "Audio Chapter Splitter", "audio-x-generic-symbolic", (const char*[]){ "media", "chapter", "splitter", "audio", NULL }, "audio-chapter-splitter", NULL },
    { NULL }
};

static const HelvetiaTool tools_video[] = {
    { "video_player", "Video Player", "Video Player", "video-x-generic-symbolic", (const char*[]){ "player", "video", "media", NULL }, "video-player", NULL },
    { "video_converter", "Video Converter", "MP4, MKV, WEBM, AVI, MOV, HEVC, AV1", "video-x-generic-symbolic", (const char*[]){ "video", "media", "converter", NULL }, "video-converter", NULL },
    { "video_trimmer", "Video Trimmer", "Video Trimmer", "video-x-generic-symbolic", (const char*[]){ "video", "media", "trimmer", NULL }, "video-trimmer", NULL },
    { "video_cutter", "Video Cutter", "Video Cutter", "video-x-generic-symbolic", (const char*[]){ "video", "media", "cutter", NULL }, "video-cutter", NULL },
    { "video_merger", "Video Merger", "Video Merger", "video-x-generic-symbolic", (const char*[]){ "video", "media", "merger", NULL }, "video-merger", NULL },
    { "video_splitter", "Video Splitter", "Video Splitter", "video-x-generic-symbolic", (const char*[]){ "video", "splitter", "media", NULL }, "video-splitter", NULL },
    { "video_compressor", "Video Compressor", "Video Compressor", "video-x-generic-symbolic", (const char*[]){ "video", "media", "compressor", NULL }, "video-compressor", NULL },
    { "video_resizer", "Video Resizer", "Video Resizer", "video-x-generic-symbolic", (const char*[]){ "resizer", "video", "media", NULL }, "video-resizer", NULL },
    { "video_cropper", "Video Cropper", "Video Cropper", "video-x-generic-symbolic", (const char*[]){ "video", "media", "cropper", NULL }, "video-cropper", NULL },
    { "video_rotator", "Video Rotator", "Video Rotator", "video-x-generic-symbolic", (const char*[]){ "video", "media", "rotator", NULL }, "video-rotator", NULL },
    { "video_flipper", "Video Flipper", "Video Flipper", "video-x-generic-symbolic", (const char*[]){ "video", "media", "flipper", NULL }, "video-flipper", NULL },
    { "video_speed_change", "Video Speed Change", "Video Speed Change", "video-x-generic-symbolic", (const char*[]){ "change", "video", "media", "speed", NULL }, "video-speed-change", NULL },
    { "video_reverse", "Video Reverse", "Video Reverse", "video-x-generic-symbolic", (const char*[]){ "video", "media", "reverse", NULL }, "video-reverse", NULL },
    { "video_stabilizer", "Video Stabilizer", "Video Stabilizer", "video-x-generic-symbolic", (const char*[]){ "video", "media", "stabilizer", NULL }, "video-stabilizer", NULL },
    { "video_frame_extractor", "Video Frame Extractor", "Video Frame Extractor", "video-x-generic-symbolic", (const char*[]){ "video", "frame", "media", "extractor", NULL }, "video-frame-extractor", NULL },
    { "video_to_gif", "Video to GIF", "Video to GIF", "video-x-generic-symbolic", (const char*[]){ "video", "media", "gif", NULL }, "video2gif", NULL },
    { "gif_to_video", "GIF to Video", "GIF to Video", "video-x-generic-symbolic", (const char*[]){ "video", "media", "gif", NULL }, "gif2video", NULL },
    { "video_to_audio", "Video to Audio", "Video to Audio", "audio-x-generic-symbolic", (const char*[]){ "video", "media", "audio", NULL }, "video2audio", NULL },
    { "video_to_images", "Video to Images", "Video to Images", "video-x-generic-symbolic", (const char*[]){ "video", "media", "images", NULL }, "video2images", NULL },
    { "images_to_video", "Images to Video", "Images to Video", "video-x-generic-symbolic", (const char*[]){ "video", "media", "images", NULL }, "images2video", NULL },
    { "video_thumbnail_generator", "Video Thumbnail Generator", "Video Thumbnail Generator", "video-x-generic-symbolic", (const char*[]){ "generator", "video", "media", "thumbnail", NULL }, "video-thumbnail-generator", NULL },
    { "video_metadata_editor", "Video Metadata Editor", "Video Metadata Editor", "video-x-generic-symbolic", (const char*[]){ "video", "media", "editor", "metadata", NULL }, "video-metadata-editor", NULL },
    { "video_chapter_editor", "Video Chapter Editor", "Video Chapter Editor", "video-x-generic-symbolic", (const char*[]){ "video", "chapter", "editor", "media", NULL }, "video-chapter-editor", NULL },
    { "video_subtitle_muxer", "Video Subtitle Muxer", "Video Subtitle Muxer", "video-x-generic-symbolic", (const char*[]){ "video", "media", "muxer", "subtitle", NULL }, "video-subtitle-muxer", NULL },
    { "video_subtitle_extractor", "Video Subtitle Extractor", "Video Subtitle Extractor", "video-x-generic-symbolic", (const char*[]){ "video", "media", "subtitle", "extractor", NULL }, "video-subtitle-extractor", NULL },
    { "video_watermark", "Video Watermark", "Video Watermark", "video-x-generic-symbolic", (const char*[]){ "video", "media", "watermark", NULL }, "video-watermark", NULL },
    { "video_overlay", "Video Overlay", "Video Overlay", "video-x-generic-symbolic", (const char*[]){ "overlay", "video", "media", NULL }, "video-overlay", NULL },
    { "video_color_correction", "Video Color Correction", "Video Color Correction", "video-x-generic-symbolic", (const char*[]){ "color", "video", "correction", "media", NULL }, "video-color-correction", NULL },
    { "video_bitrate_calculator", "Video Bitrate Calculator", "Video Bitrate Calculator", "video-x-generic-symbolic", (const char*[]){ "calculator", "video", "media", "bitrate", NULL }, "video-bitrate-calculator", NULL },
    { "video_codec_info", "Video Codec Info", "Video Codec Info", "video-x-generic-symbolic", (const char*[]){ "codec", "video", "media", "info", NULL }, "video-codec-info", NULL },
    { "video_screen_recorder", "Video Screen Recorder", "Video Screen Recorder", "video-x-generic-symbolic", (const char*[]){ "video", "media", "recorder", "screen", NULL }, "video-screen-recorder", NULL },
    { "webcam_recorder", "Webcam Recorder", "Webcam Recorder", "multimedia-video-player-symbolic", (const char*[]){ "webcam", "media", "recorder", NULL }, "webcam-recorder", NULL },
    { "dvd_blu_ray_ripper", "DVD / Blu-ray Ripper", "offline, decryption-free sources only", "multimedia-video-player-symbolic", (const char*[]){ "bluray", "media", "dvd", "ripper", NULL }, "dvd-blu-ray-ripper", NULL },
    { NULL }
};

static const HelvetiaTool tools_subtitles[] = {
    { "subtitle_editor", "Subtitle Editor", "Subtitle Editor", "multimedia-video-player-symbolic", (const char*[]){ "media", "editor", "subtitle", NULL }, "subtitle-editor", NULL },
    { "subtitle_converter", "Subtitle Converter", "SRT, VTT, ASS, SSA", "multimedia-video-player-symbolic", (const char*[]){ "media", "converter", "subtitle", NULL }, "subtitle-converter", NULL },
    { "subtitle_sync", "Subtitle Sync", "Subtitle Sync", "multimedia-video-player-symbolic", (const char*[]){ "media", "subtitle", "sync", NULL }, "subtitle-sync", NULL },
    { "subtitle_translator", "Subtitle Translator", "offline, Argos", "multimedia-video-player-symbolic", (const char*[]){ "media", "translator", "subtitle", NULL }, "subtitle-translator", NULL },
    { NULL }
};

static const HelvetiaSubcategory media_subcategories[] = {
    { "Audio", tools_audio },
    { "Video", tools_video },
    { "Subtitles", tools_subtitles },
    { NULL, NULL }
};

static const HelvetiaModule media_module = {
    .id            = "media",
    .name          = "Media",
    .icon_name     = "multimedia-video-player-symbolic",
    .description   = "Audio and video, offline via FFmpeg.",
    .subcategories = media_subcategories,
    .create_view   = NULL,
    .on_activate   = NULL,
    .on_deactivate = NULL,
    .on_shutdown   = NULL,
};

const HelvetiaModule *helvetia_media_get_module(void) {
    return &media_module;
}
